#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Machine Payments Summit — Exercise Setup
# Usage: git clone https://github.com/dansmith-stripe/sa-summit-26-setup.git && bash sa-summit-26-setup/setup.sh
# ─────────────────────────────────────────────────────────────────────────────

ENV_FILE="$HOME/.machine-payments-summit.env"

# Colors
BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
RESET="\033[0m"

# ── Directory key (restricted, read-only — safe to embed) ────────────────────
DIRECTORY_API_KEY="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"

# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Machine Payments Summit — Exercise Setup${RESET}"
echo "────────────────────────────────────────────"
echo ""
echo "This sets up your sandbox credentials and registers the"
echo "summit-booking-demo MCP server with Claude Code."
echo ""

# ── Prerequisite reminder ────────────────────────────────────────────────────

echo -e "${YELLOW}Prerequisite:${RESET} Make sure you have a passkey on your Link account."
echo "  Add one at https://app.link.com/settings → Passkeys before continuing."
echo ""
read -rp "Press Enter when ready... "
echo ""

# ── Prompt for values ────────────────────────────────────────────────────────

echo -e "${BOLD}You'll be prompted for 3 values:${RESET}"
echo ""
printf "  %-20s %s\n" "LDAP handle"    "Your lowercase Stripe handle (e.g. jdoe)"
printf "  %-20s %s\n" "Profile ID"     "Dashboard → Settings → Profile → Network ID (starts with profile_)"
printf "  %-20s %s\n" "Secret key"     "Dashboard → Developers → API keys, test mode (starts with sk_test_)"
echo ""

# LDAP handle
read -rp "Stripe LDAP handle: " LDAP_HANDLE
if [[ -z "$LDAP_HANDLE" ]]; then
  echo -e "${RED}✗ LDAP handle cannot be empty.${RESET}" && exit 1
fi

# Profile ID
read -rp "Stripe Profile ID:  " PROFILE_ID
if [[ "$PROFILE_ID" != profile_* ]]; then
  echo -e "${YELLOW}⚠ Profile ID should start with profile_ — continuing anyway.${RESET}"
fi

# Secret key (hidden input, validated)
while true; do
  read -rp "Stripe secret key:  " SECRET_KEY
  echo ""
  if [[ "$SECRET_KEY" == sk_test_* ]]; then
    echo -e "${GREEN}✓ Key received (${#SECRET_KEY} characters)${RESET}"
    break
  fi
  echo -e "${YELLOW}⚠ Must start with sk_test_ — try again.${RESET}"
done

# ── Write env file ───────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Machine Payments Summit — generated by setup.sh
# Do not commit or share this file.
export LDAP_HANDLE=${LDAP_HANDLE}
export STRIPE_PROFILE_ID=${PROFILE_ID}
export STRIPE_SECRET_KEY=${SECRET_KEY}
export STRIPE_API_KEY=${DIRECTORY_API_KEY}
EOF

chmod 600 "$ENV_FILE"
echo ""
echo -e "${GREEN}✓ Credentials saved to ${ENV_FILE}${RESET}"

# ── Auto-source on shell startup ─────────────────────────────────────────────

SOURCE_LINE="source \"${ENV_FILE}\""

for RC_FILE in "$HOME/.zshrc" "$HOME/.bashrc"; do
  if [[ -f "$RC_FILE" ]] && ! grep -qF "$ENV_FILE" "$RC_FILE"; then
    echo "" >> "$RC_FILE"
    echo "# Machine Payments Summit" >> "$RC_FILE"
    echo "$SOURCE_LINE" >> "$RC_FILE"
    echo -e "${GREEN}✓ Auto-source added to ${RC_FILE}${RESET}"
  fi
done

# Apply to the current shell session immediately
# shellcheck disable=SC1090
source "$ENV_FILE"
echo -e "${GREEN}✓ Variables exported in current shell${RESET}"

# ── Register MCP server with Claude Code ────────────────────────────────────

echo ""
echo "Registering summit-booking-demo MCP server..."

# Remove any stale registration first (idempotent)
claude mcp remove summit-booking-demo 2>/dev/null || true

# TODO: replace with actual MCP server command or --url
claude mcp add summit-booking-demo REPLACE_WITH_MCP_COMMAND_OR_URL

echo -e "${GREEN}✓ MCP server registered${RESET}"

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Setup complete! You're ready to go.${RESET}"
echo ""
echo "Run these commands in this terminal:"
echo ""
echo "  claude mcp list   # confirm summit-booking-demo shows ✓ Connected"
echo "  claude"
echo ""
