#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Machine Payments Summit — Exercise Setup
# Usage: git clone https://github.com/dansmith-stripe/sa-summit-26-setup.git && bash sa-summit-26-setup/setup.sh
# ─────────────────────────────────────────────────────────────────────────────

ENV_FILE="$HOME/.machine-payments-summit.env"

# Colors
BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
RESET="\033[0m"

# ── Directory key (restricted, read-only — safe to embed) ────────────────────
DIRECTORY_API_KEY="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"

# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Machine Payments Summit — Exercise Setup${RESET}"
echo "────────────────────────────────────────────"
echo ""
echo "This sets up your sandbox credentials and registers the"
echo "summit-booking-demo MCP server with Claude Code."
echo ""

# ── Prerequisite reminder ────────────────────────────────────────────────────

echo -e "${YELLOW}Prerequisite:${RESET} Make sure you have a passkey on your Link account."
echo "  Add one at https://app.link.com/settings → Passkeys before continuing."
echo ""
read -rp "Press Enter when ready... "
echo ""

# ── Load existing values if re-running ───────────────────────────────────────

LDAP_HANDLE=""
PROFILE_ID=""
SECRET_KEY=""

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE" 2>/dev/null || true
  LDAP_HANDLE="${LDAP_HANDLE:-}"
  PROFILE_ID="${MP_DEMO_STRIPE_PROFILE_ID:-}"
  SECRET_KEY="${MP_DEMO_STRIPE_SECRET_KEY:-}"
  echo -e "${YELLOW}Existing credentials found — press Enter to keep each value.${RESET}"
  echo ""
fi

# ── Prompt for values ────────────────────────────────────────────────────────

echo -e "${BOLD}You'll be prompted for 3 values:${RESET}"
echo ""
printf "  %-20s %s\n" "LDAP handle"    "Your lowercase Stripe handle (e.g. jdoe)"
printf "  %-20s %s\n" "Profile ID"     "Dashboard → Settings → Profile → Network ID (starts with profile_)"
printf "  %-20s %s\n" "Secret key"     "Dashboard → Developers → API keys, test mode (starts with sk_test_)"
echo ""

# LDAP handle
read -rp "Stripe LDAP handle${LDAP_HANDLE:+ [${LDAP_HANDLE}]}: " INPUT
LDAP_HANDLE="${INPUT:-$LDAP_HANDLE}"
if [[ -z "$LDAP_HANDLE" ]]; then
  echo -e "${RED}✗ LDAP handle cannot be empty.${RESET}" && exit 1
fi

# Profile ID
read -rp "Stripe Profile ID${PROFILE_ID:+ [${PROFILE_ID}]}: " INPUT
PROFILE_ID="${INPUT:-$PROFILE_ID}"
if [[ "$PROFILE_ID" != profile_* ]]; then
  echo -e "${YELLOW}⚠ Profile ID should start with profile_ — continuing anyway.${RESET}"
fi

# Secret key
while true; do
  read -rp "Stripe secret key${SECRET_KEY:+ [${SECRET_KEY}]}: " INPUT
  SECRET_KEY="${INPUT:-$SECRET_KEY}"
  if [[ "$SECRET_KEY" == sk_test_* ]]; then
    break
  fi
  echo -e "${YELLOW}⚠ Must start with sk_test_ — try again.${RESET}"
done

# ── Write env file ───────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Machine Payments Summit — generated by setup.sh
# Do not commit or share this file.
export LDAP_HANDLE=${LDAP_HANDLE}
export MP_DEMO_TEAM_ID=summit-${LDAP_HANDLE}-e2e
export MP_DEMO_STRIPE_PROFILE_ID=${PROFILE_ID}
export MP_DEMO_STRIPE_SECRET_KEY=${SECRET_KEY}
export STRIPE_DIRECTORY_API_KEY=${DIRECTORY_API_KEY}
export CLAUDE_CODE_DANGEROUSLY_ALLOWED_MCP_SERVERS=summit-booking-demo
EOF

chmod 600 "$ENV_FILE"
echo ""
echo -e "${GREEN}✓ Credentials saved to ${ENV_FILE}${RESET}"

# ── Install / upgrade Stripe CLI and Directory plugin ────────────────────────

echo ""
echo "Checking Stripe CLI..."

if command -v stripe &>/dev/null; then
  brew upgrade stripe 2>/dev/null || true
  echo -e "${GREEN}✓ Stripe CLI up to date${RESET}"
else
  echo -e "${YELLOW}Installing Stripe CLI via Homebrew...${RESET}"
  brew install stripe/stripe-cli/stripe
  echo -e "${GREEN}✓ Stripe CLI installed${RESET}"
fi

echo "Installing Stripe Directory plugin..."
stripe plugin install directory 2>/dev/null || stripe plugin upgrade directory 2>/dev/null || true
echo -e "${GREEN}✓ Directory plugin ready${RESET}"

# ── Register summit-directory Stripe CLI profile ─────────────────────────────

STRIPE_CONFIG="$HOME/.config/stripe/config.toml"

if [[ -f "$STRIPE_CONFIG" ]]; then
  # Remove any existing summit-directory section (idempotent)
  python3 - "$STRIPE_CONFIG" "$DIRECTORY_API_KEY" <<'PYEOF'
import sys, re

config_path = sys.argv[1]
api_key     = sys.argv[2]

with open(config_path, "r") as f:
    content = f.read()

# Remove existing [summit-directory] block if present
content = re.sub(
    r"\[summit-directory\][^\[]*",
    "",
    content,
    flags=re.DOTALL
).rstrip() + "\n"

# Append new block
content += f"""
[summit-directory]
account_id = 'acct_1Ty0D9PO6vgg8ena'
device_name = 'summit-directory'
display_name = 'summit-directory'
live_mode_api_key = '{api_key}'
profile_name = 'summit-directory'
"""

with open(config_path, "w") as f:
    f.write(content)

print("ok")
PYEOF
  echo -e "${GREEN}✓ Stripe CLI profile 'summit-directory' registered${RESET}"
else
  echo -e "${YELLOW}⚠ ~/.config/stripe/config.toml not found — skipping directory profile.${RESET}"
  echo "  Run 'stripe login' first, then re-run this script."
fi

# ── Auto-source on shell startup ─────────────────────────────────────────────

SOURCE_LINE="source \"${ENV_FILE}\""

for RC_FILE in "$HOME/.zshrc" "$HOME/.bashrc"; do
  if [[ -f "$RC_FILE" ]] && ! grep -qF "$ENV_FILE" "$RC_FILE"; then
    echo "" >> "$RC_FILE"
    echo "# Machine Payments Summit" >> "$RC_FILE"
    echo "$SOURCE_LINE" >> "$RC_FILE"
    echo -e "${GREEN}✓ Auto-source added to ${RC_FILE}${RESET}"
  fi
done

echo -e "${GREEN}✓ Variables will load automatically in all new terminals${RESET}"

# ── Register MCP server with Claude Code ────────────────────────────────────

echo ""
echo "Registering summit-booking-demo MCP server..."

# Remove any stale registration first (idempotent)
claude mcp remove summit-booking-demo >/dev/null 2>&1 || true

# Register with HTTP transport — headers use single quotes so raw ${VAR}
# references are stored in Claude config, not the actual secret values.
claude mcp add \
  --transport http \
  --scope user \
  summit-booking-demo \
  https://machine-payments.stripedemos.com/mcp \
  --header 'X-Demo-Stripe-Secret-Key: ${MP_DEMO_STRIPE_SECRET_KEY}' \
  --header 'X-Demo-Stripe-Profile-Id: ${MP_DEMO_STRIPE_PROFILE_ID}' \
  --header 'X-Demo-Team-Id: ${MP_DEMO_TEAM_ID}'

echo -e "${GREEN}✓ MCP server registered${RESET}"

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Setup complete!${RESET}"
echo ""
echo "Activate in this terminal:"
echo ""
echo -e "  ${BOLD}source ~/.machine-payments-summit.env${RESET}"
echo ""
echo "Then verify and launch Claude:"
echo ""
echo "  claude mcp list   # confirm summit-booking-demo shows ✓ Connected"
echo "  claude"
echo ""
